server:
  port: 9001

spring:
  cloud:
    gateway:
      routes:
        - id: user_auth
          uri: http://localhost:8001
          predicates:
            - Path=/user/**

        - id: house_post
          uri: http://localhost:8002
          predicates:
            - Path=/post/**
# nacos
    nacos:
      server-addr: localhost:8848
      discovery:
        service: Gateway