server:
  port: 9001

spring:
  cloud:
    gateway:
      routes:
        - id: UserService
          uri:  lb://UserService
          predicates:
            - Path=/user/**

        - id: HouseService
          uri: lb://HouseService
          predicates:
            - Path=/house/**

        - id: ReportService
          uri: lb://ReportService
          predicates:
            - Path=/report/**

        - id: NewsService
          uri: lb://NewsService
          predicates:
            - Path=/news/**

        - id: AuditService
          uri: lb://AuditService
          predicates:
            - Path=/audit/**

        - id: SystemService
          uri: lb://SystemService
          predicates:
            - Path=/sys/**
#            - Path=/message/**

#  datasource:
#    url: jdbc:mysql://82.157.113.175:3306/UkraineAssistance
#    username: root
#    password: ho/uI;oz-13?
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 20
#        max-wait: -1
#    password: syhxsqqaxfdyhh
#
#mybatis-plus:
#  mapper-locations: classpath:DaoXML/*.xml
# nacos
    nacos:
      server-addr: 139.9.231.20:8848
      discovery:
        service: Gateway
