server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://82.157.113.175:3306/UkraineAssistance
    username: root
    password: ho/uI;oz-13?
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
    password: syhxsqqaxfdyhh