server:
  port: 8012

spring:
  datasource:
    url: jdbc:mysql://121.37.70.144:3306/UAHouse
    username: root
    password: Zjt@123456
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 20
#        max-wait: -1

  houseService:
    houseObjtypeId: 10006

  cloud:
    nacos:
      server-addr: 139.9.231.20:8848
      discovery:
        service: HouseService


