server:
  port: 8009

spring:
  datasource:
    url: jdbc:mysql://121.37.70.144:3306/UA
    username: root
    password: Zjt@123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
#    password: syhxsqqaxfdyhh
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  reportService:
    reportObjtypeId: 10010

  #    nacos
  cloud:
    nacos:
      server-addr: 139.9.231.20:8848
      discovery:
        service: ReportService

mybatis-plus:
  mapper-locations: classpath:DaoXML/*.xml
