server:
  port: 8004

spring:
  datasource:
    url: jdbc:mysql://121.37.70.144:3306/UA
    username: root
    password: Zjt@123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1

  #    nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: AuditService

mybatis-plus:
  mapper-locations: classpath:DaoXML/*.xml
