server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://82.157.113.175:3306/UkraineAssistance
    username: root
    password: ho/uI;oz-13?
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
    password: syhxsqqaxfdyhh
  mail:
    host: smtp.qq.com
    password: riunoiabplazhfgf
    default-encoding: UTF-8
    port: 587
    username: 1533152445@qq.com

  userService:
    normalUserRoleName: NORMAL_USER
    activeFilePath: E:\\ukraine-bhelper\\backend\\UkraineAid\\Service\\UserService\\src\\main\\resources\\static\\Active.html
    userObjectId: 10000
    roleObjtypeId: 10001
    userRoleObjectId: 10002




#    nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: UserService

mybatis-plus:
  mapper-locations: classpath:DaoXML/*.xml

