server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://121.37.70.144:3306/UA
    username: root
    password: Zjt@123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
#    password: syhxsqqaxfdyhh
  mail:
    host: smtp.qq.com
    password: riunoiabplazhfgf
    default-encoding: UTF-8
    port: 587
    username: 1533152445@qq.com

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  userService:
    normalUserRoleName: NORMAL_USER
    activeFilePath: E:\\ukraine-bhelper\\backend\\UkraineAid\\Service\\UserService\\src\\main\\resources\\static\\Active.html
    userObjtypeId: 10000
    roleObjtypeId: 10001
    permissionObjtypeId: 10002
    userRoleObjtypeId: 10003
    rolePermissionObjtypeId: 10004

    addOperation: 10000
    updateOperation: 10001




#    nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: UserService

mybatis-plus:
  mapper-locations: classpath:DaoXML/*.xml

